# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Mon Dec 26 00:26:02 2011
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(641, 505)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "NRT", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.widget = QtGui.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 11, 621, 451))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_8.setMargin(0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.comboBgr = QtGui.QGroupBox(self.widget)
        self.comboBgr.setTitle(QtGui.QApplication.translate("MainWindow", "Choose Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBgr.setObjectName(_fromUtf8("comboBgr"))
        self.widget1 = QtGui.QWidget(self.comboBgr)
        self.widget1.setGeometry(QtCore.QRect(20, 40, 148, 257))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.widget1)
        self.verticalLayout_9.setMargin(0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.graphList = QtGui.QComboBox(self.widget1)
        self.graphList.setObjectName(_fromUtf8("graphList"))
        self.graphList.addItem(_fromUtf8(""))
        self.graphList.setItemText(0, QtGui.QApplication.translate("MainWindow", "B.-A. with remove", None, QtGui.QApplication.UnicodeUTF8))
        self.graphList.addItem(_fromUtf8(""))
        self.graphList.setItemText(1, QtGui.QApplication.translate("MainWindow", "B.-A.", None, QtGui.QApplication.UnicodeUTF8))
        self.graphList.addItem(_fromUtf8(""))
        self.graphList.setItemText(2, QtGui.QApplication.translate("MainWindow", "Flower with remove", None, QtGui.QApplication.UnicodeUTF8))
        self.graphList.addItem(_fromUtf8(""))
        self.graphList.setItemText(3, QtGui.QApplication.translate("MainWindow", "Flower", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_9.addWidget(self.graphList)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.chackGraph = QtGui.QCheckBox(self.widget1)
        self.chackGraph.setText(QtGui.QApplication.translate("MainWindow", "Graph", None, QtGui.QApplication.UnicodeUTF8))
        self.chackGraph.setObjectName(_fromUtf8("chackGraph"))
        self.verticalLayout.addWidget(self.chackGraph)
        self.checkBtw = QtGui.QCheckBox(self.widget1)
        self.checkBtw.setText(QtGui.QApplication.translate("MainWindow", "Betweenness", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBtw.setObjectName(_fromUtf8("checkBtw"))
        self.verticalLayout.addWidget(self.checkBtw)
        self.checkProb = QtGui.QCheckBox(self.widget1)
        self.checkProb.setText(QtGui.QApplication.translate("MainWindow", "Probability", None, QtGui.QApplication.UnicodeUTF8))
        self.checkProb.setObjectName(_fromUtf8("checkProb"))
        self.verticalLayout.addWidget(self.checkProb)
        self.checkDeghist = QtGui.QCheckBox(self.widget1)
        self.checkDeghist.setText(QtGui.QApplication.translate("MainWindow", "Degree histogam", None, QtGui.QApplication.UnicodeUTF8))
        self.checkDeghist.setObjectName(_fromUtf8("checkDeghist"))
        self.verticalLayout.addWidget(self.checkDeghist)
        self.checkRankdisp = QtGui.QCheckBox(self.widget1)
        self.checkRankdisp.setText(QtGui.QApplication.translate("MainWindow", "Rank distribution", None, QtGui.QApplication.UnicodeUTF8))
        self.checkRankdisp.setObjectName(_fromUtf8("checkRankdisp"))
        self.verticalLayout.addWidget(self.checkRankdisp)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.checkNyu = QtGui.QCheckBox(self.widget1)
        self.checkNyu.setText(QtGui.QApplication.translate("MainWindow", "Nyu", None, QtGui.QApplication.UnicodeUTF8))
        self.checkNyu.setObjectName(_fromUtf8("checkNyu"))
        self.verticalLayout_2.addWidget(self.checkNyu)
        self.checkClust = QtGui.QCheckBox(self.widget1)
        self.checkClust.setText(QtGui.QApplication.translate("MainWindow", "Clustering", None, QtGui.QApplication.UnicodeUTF8))
        self.checkClust.setObjectName(_fromUtf8("checkClust"))
        self.verticalLayout_2.addWidget(self.checkClust)
        self.checkSP = QtGui.QCheckBox(self.widget1)
        self.checkSP.setText(QtGui.QApplication.translate("MainWindow", "Shortpath", None, QtGui.QApplication.UnicodeUTF8))
        self.checkSP.setObjectName(_fromUtf8("checkSP"))
        self.verticalLayout_2.addWidget(self.checkSP)
        self.checkAssort = QtGui.QCheckBox(self.widget1)
        self.checkAssort.setText(QtGui.QApplication.translate("MainWindow", "Assortativity", None, QtGui.QApplication.UnicodeUTF8))
        self.checkAssort.setObjectName(_fromUtf8("checkAssort"))
        self.verticalLayout_2.addWidget(self.checkAssort)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_9.addLayout(self.verticalLayout_3)
        self.horizontalLayout_7.addWidget(self.comboBgr)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.idataBgr = QtGui.QGroupBox(self.widget)
        self.idataBgr.setTitle(QtGui.QApplication.translate("MainWindow", "Initial Data", None, QtGui.QApplication.UnicodeUTF8))
        self.idataBgr.setObjectName(_fromUtf8("idataBgr"))
        self.widget2 = QtGui.QWidget(self.idataBgr)
        self.widget2.setGeometry(QtCore.QRect(10, 30, 151, 114))
        self.widget2.setObjectName(_fromUtf8("widget2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.widget2)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.widget2)
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.startr = QtGui.QLineEdit(self.widget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startr.sizePolicy().hasHeightForWidth())
        self.startr.setSizePolicy(sizePolicy)
        self.startr.setObjectName(_fromUtf8("startr"))
        self.horizontalLayout_2.addWidget(self.startr)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_2 = QtGui.QLabel(self.widget2)
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "End", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_5.addWidget(self.label_2)
        self.endr = QtGui.QLineEdit(self.widget2)
        self.endr.setObjectName(_fromUtf8("endr"))
        self.horizontalLayout_5.addWidget(self.endr)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.widget2)
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Step", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.stepr = QtGui.QLineEdit(self.widget2)
        self.stepr.setObjectName(_fromUtf8("stepr"))
        self.horizontalLayout_4.addWidget(self.stepr)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_4 = QtGui.QLabel(self.widget2)
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Iteration Count", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_3.addWidget(self.label_4)
        self.numr = QtGui.QLineEdit(self.widget2)
        self.numr.setObjectName(_fromUtf8("numr"))
        self.horizontalLayout_3.addWidget(self.numr)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_6.addWidget(self.idataBgr)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gdataBgr_BA = QtGui.QGroupBox(self.widget)
        self.gdataBgr_BA.setTitle(QtGui.QApplication.translate("MainWindow", "Graph Data", None, QtGui.QApplication.UnicodeUTF8))
        self.gdataBgr_BA.setObjectName(_fromUtf8("gdataBgr_BA"))
        self.widget3 = QtGui.QWidget(self.gdataBgr_BA)
        self.widget3.setGeometry(QtCore.QRect(10, 20, 74, 172))
        self.widget3.setObjectName(_fromUtf8("widget3"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.widget3)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_11 = QtGui.QLabel(self.widget3)
        self.label_11.setText(QtGui.QApplication.translate("MainWindow", "m", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_12.addWidget(self.label_11)
        self.mBA = QtGui.QLineEdit(self.widget3)
        self.mBA.setObjectName(_fromUtf8("mBA"))
        self.horizontalLayout_12.addWidget(self.mBA)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_5 = QtGui.QLabel(self.widget3)
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "m0", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_6.addWidget(self.label_5)
        self.m0BA = QtGui.QLineEdit(self.widget3)
        self.m0BA.setObjectName(_fromUtf8("m0BA"))
        self.horizontalLayout_6.addWidget(self.m0BA)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_12 = QtGui.QLabel(self.widget3)
        self.label_12.setText(QtGui.QApplication.translate("MainWindow", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_13.addWidget(self.label_12)
        self.nBA = QtGui.QLineEdit(self.widget3)
        self.nBA.setObjectName(_fromUtf8("nBA"))
        self.horizontalLayout_13.addWidget(self.nBA)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_8 = QtGui.QLabel(self.widget3)
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "r", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_9.addWidget(self.label_8)
        self.rBA = QtGui.QLineEdit(self.widget3)
        self.rBA.setObjectName(_fromUtf8("rBA"))
        self.horizontalLayout_9.addWidget(self.rBA)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_9 = QtGui.QLabel(self.widget3)
        self.label_9.setText(QtGui.QApplication.translate("MainWindow", "p", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_10.addWidget(self.label_9)
        self.pBA = QtGui.QLineEdit(self.widget3)
        self.pBA.setObjectName(_fromUtf8("pBA"))
        self.horizontalLayout_10.addWidget(self.pBA)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_10 = QtGui.QLabel(self.widget3)
        self.label_10.setText(QtGui.QApplication.translate("MainWindow", "di", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_11.addWidget(self.label_10)
        self.diBA = QtGui.QLineEdit(self.widget3)
        self.diBA.setObjectName(_fromUtf8("diBA"))
        self.horizontalLayout_11.addWidget(self.diBA)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addWidget(self.gdataBgr_BA)
        self.gdataBgr_FL = QtGui.QGroupBox(self.widget)
        self.gdataBgr_FL.setEnabled(True)
        self.gdataBgr_FL.setTitle(QtGui.QApplication.translate("MainWindow", "Graph Data", None, QtGui.QApplication.UnicodeUTF8))
        self.gdataBgr_FL.setObjectName(_fromUtf8("gdataBgr_FL"))
        self.widget4 = QtGui.QWidget(self.gdataBgr_FL)
        self.widget4.setGeometry(QtCore.QRect(10, 20, 81, 143))
        self.widget4.setObjectName(_fromUtf8("widget4"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.widget4)
        self.verticalLayout_7.setMargin(0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_17 = QtGui.QLabel(self.widget4)
        self.label_17.setText(QtGui.QApplication.translate("MainWindow", "x", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_15.addWidget(self.label_17)
        self.xFL = QtGui.QLineEdit(self.widget4)
        self.xFL.setObjectName(_fromUtf8("xFL"))
        self.horizontalLayout_15.addWidget(self.xFL)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_15 = QtGui.QLabel(self.widget4)
        self.label_15.setText(QtGui.QApplication.translate("MainWindow", "y", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_8.addWidget(self.label_15)
        self.yFL = QtGui.QLineEdit(self.widget4)
        self.yFL.setObjectName(_fromUtf8("yFL"))
        self.horizontalLayout_8.addWidget(self.yFL)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_13 = QtGui.QLabel(self.widget4)
        self.label_13.setText(QtGui.QApplication.translate("MainWindow", "n", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_14.addWidget(self.label_13)
        self.nFL = QtGui.QLineEdit(self.widget4)
        self.nFL.setObjectName(_fromUtf8("nFL"))
        self.horizontalLayout_14.addWidget(self.nFL)
        self.verticalLayout_7.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_14 = QtGui.QLabel(self.widget4)
        self.label_14.setText(QtGui.QApplication.translate("MainWindow", "r", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_16.addWidget(self.label_14)
        self.rFL = QtGui.QLineEdit(self.widget4)
        self.rFL.setObjectName(_fromUtf8("rFL"))
        self.horizontalLayout_16.addWidget(self.rFL)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_16 = QtGui.QLabel(self.widget4)
        self.label_16.setText(QtGui.QApplication.translate("MainWindow", "p", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_17.addWidget(self.label_16)
        self.pFL = QtGui.QLineEdit(self.widget4)
        self.pFL.setObjectName(_fromUtf8("pFL"))
        self.horizontalLayout_17.addWidget(self.pFL)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.horizontalLayout.addWidget(self.gdataBgr_FL)
        self.magikBtn = QtGui.QPushButton(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.magikBtn.sizePolicy().hasHeightForWidth())
        self.magikBtn.setSizePolicy(sizePolicy)
        self.magikBtn.setText(QtGui.QApplication.translate("MainWindow", "GO", None, QtGui.QApplication.UnicodeUTF8))
        self.magikBtn.setObjectName(_fromUtf8("magikBtn"))
        self.horizontalLayout.addWidget(self.magikBtn)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_7.addLayout(self.verticalLayout_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.buidProgress = QtGui.QProgressBar(self.widget)
        self.buidProgress.setProperty("value", 24)
        self.buidProgress.setObjectName(_fromUtf8("buidProgress"))
        self.verticalLayout_8.addWidget(self.buidProgress)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 641, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExport = QtGui.QAction(MainWindow)
        self.actionExport.setText(QtGui.QApplication.translate("MainWindow", "Export", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExport.setObjectName(_fromUtf8("actionExport"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setText(QtGui.QApplication.translate("MainWindow", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionTutorial = QtGui.QAction(MainWindow)
        self.actionTutorial.setText(QtGui.QApplication.translate("MainWindow", "Tutorial", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTutorial.setObjectName(_fromUtf8("actionTutorial"))
        self.menuFile.addAction(self.actionExport)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionTutorial)
        self.menuHelp.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        pass

